---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: smarshops/delivery-ci-fly

inputs:
  - name: delivery-pop-automation

run:
  path: bash
  args: [delivery-pop-automation/ci/tasks/create-pop-release-candidate/task.sh]

params:
  GIT_PRIVATE_KEY: