---

groups:

  - name: all
    jobs:
      - set-pipeline
      - pop-test

jobs:

  - name: set-pipeline
    serial: true
    plan:
      - in_parallel:
          - get: delivery-pop-automation
            trigger: true
      - set_pipeline: pop-test
        file: delivery-pop-automation/pipeline.yml

  - name: pop-test
    serial: true
    plan:
      - in_parallel:
          - get: delivery-pop-automation
            passed: [ set-pipeline ]
          - get: delivery-ci-all-image
      - in_parallel:
          - task: pop-test
            attempts: 1
            file: delivery-pop-automation/ci/tasks/create-pop-release-candidate/task.yml
            image: delivery-ci-all-image

resources:

  - name: delivery-pop-automation
    type: git
    source:
      private_key: ((github_private_key))
      uri: git@github.com:Smarsh/delivery-pop-automation.git
      branch: master

  - name: delivery-ci-all-image
    type: registry-image
    source:
      repository: smarshops/delivery-ci-all
