---

groups:

  - name: all
    jobs:
      - set-pipeline
      - pop-test

jobs:

  - name: set-pipeline
    serial: true
    plan:
      - in_parallel:
          - get: delivery-tenants-api
            trigger: true
      - set_pipeline: pop-test
        file: delivery-tenants-api/ci/nuke-ea-lite-pipeline.yml
        var_files:
          - delivery-tenants-api/ci/vars/platform-delivery-staging-aws-us-west-2.yml

  - name: nuke-ea-lite
    serial: true
    plan:
      - in_parallel:
          - get: delivery-tenants-api
            passed: [ set-pipeline ]
          - get: delivery-ci-all-image
      - in_parallel:
          - task: nuke-pipelines
            attempts: 1
            file: delivery-tenants-api/ci/tasks/poplite-nuke-pipelines/task.yml
            image: delivery-ci-all-image
            params:
              CONCOURSE_USERNAME: admin
              CONCOURSE_PASSWORD: ((app_concourse_admin_password))

resources:

  - name: delivery-tenants-api
    type: git
    source:
      private_key: ((github_private_key))
      uri: git@github.com:Smarsh/delivery-tenants-api.git
      branch: master
      ignore_paths: [version, delivery-ea-tenants-resource]

  - name: delivery-ci-all-image
    type: registry-image
    source:
      repository: smarshops/delivery-ci-all
