---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: smarshops/delivery-ci-fly

inputs:
  - name: delivery-pop-automation

run:
  path: delivery-pop-automation/ci/tasks/create-pop-release/task.sh

params:
  GIT_PRIVATE_KEY: