---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: smarshops/delivery-ci-fly
    username: ((docker-hub-username))
    password: ((docker-hub-password))

inputs:
- name: repo
- name: pop-input

run:
  path: bash
  args: ["repo/ci/tasks/create-pop-release/task.sh"]