---
platform: linux

inputs:
  - name: delivery-pop-automation

run:
  path: delivery-pop-automation/ci/tasks/pipeline-nuke-trigger-file/task.sh

params:
  GIT_PRIVATE_KEY:
  CUSTOMER:
  REGION:
  TIER:
